// ─── Données de tous les modules DAP Academy ────────────────────────────────

export interface CardData {
  icon: string;
  title: string;
  sub: string;
}

export interface ModuleData {
  num: string;
  titleL1: string;
  titleL2: string;
  domaine: string;        // clé pour getDomainColors()
  domaineLabel: string;   // texte affiché dans le badge
  meta: { duree: string; format: string; public: string; mois: string };
  objectifs: string[];
  cards: CardData[];
}

export const MODULES_DATA: ModuleData[] = [
  {
    num: '01',
    titleL1: 'Copropriétés',
    titleL2: 'RC Syndic Vivium / Axa',
    domaine: 'produits',
    domaineLabel: "Produits d'assurance",
    meta: { duree: '2h', format: 'Hybride', public: 'Tous', mois: 'Janvier 2026' },
    objectifs: [
      'Comprendre les risques spécifiques aux copropriétés',
      'Connaître le rôle et la responsabilité civile du syndic',
      'Maîtriser les produits Vivium et Axa pour ce marché',
      'Appliquer la loi du 18 juin 2018 sur la copropriété',
      'Présenter BeStronger comme argument commercial',
    ],
    cards: [
      { icon: '🏢', title: 'RC Syndic', sub: 'Responsabilité civile' },
      { icon: '📋', title: 'Vivium & Axa', sub: 'Produits copropriété' },
      { icon: '⚖️', title: 'Loi 18/06/2018', sub: 'Cadre réglementaire' },
    ],
  },
  {
    num: '02',
    titleL1: 'RC Exploitation',
    titleL2: '',
    domaine: 'produits',
    domaineLabel: "Produits d'assurance",
    meta: { duree: '2h', format: 'Hybride', public: 'Tous', mois: 'Février 2026' },
    objectifs: [
      'Distinguer RC Exploitation, RC Professionnelle et RC Produits',
      'Expliquer les garanties du produit BeStronger Pack PME',
      'Identifier les activités nécessitant une RC Exploitation',
      'Analyser un sinistre RC Exploitation et déterminer la couverture',
      'Maîtriser les exclusions courantes et les points de vigilance',
    ],
    cards: [
      { icon: '🏢', title: 'RC Exploitation', sub: 'Dommages aux tiers' },
      { icon: '📋', title: 'BeStronger Pack PME', sub: 'Produit phare DAP' },
      { icon: '⚠️', title: 'Exclusions', sub: 'Points de vigilance' },
    ],
  },
  {
    num: '03',
    titleL1: 'Gouvernance ESG',
    titleL2: '',
    domaine: 'assurances',
    domaineLabel: 'Gouvernance',
    meta: { duree: '2h', format: 'À distance', public: 'Tous', mois: 'Mars 2026' },
    objectifs: [
      'Comprendre ce que recouvrent les critères ESG',
      'Identifier les obligations réglementaires ESG pour les courtiers belges',
      'Expliquer la stratégie ESG de DAP et son lien avec DAP Solidarity',
      'Adapter son discours client pour intégrer la dimension ESG',
      'Connaître les produits d\'assurance à dimension ESG disponibles',
    ],
    cards: [
      { icon: '🌱', title: 'Critères ESG', sub: 'Environnement Social Gov.' },
      { icon: '📜', title: 'Obligations FSMA', sub: 'Réglementation belge' },
      { icon: '🤝', title: 'DAP Solidarity', sub: 'Engagement ESG concret' },
    ],
  },
  {
    num: '04',
    titleL1: "Perte d'Exploitation",
    titleL2: '',
    domaine: 'produits',
    domaineLabel: "Produits d'assurance",
    meta: { duree: '2h', format: 'À distance', public: 'Tous', mois: 'Mars 2026' },
    objectifs: [
      'Définir la perte d\'exploitation et ses deux composantes',
      'Expliquer le mécanisme d\'indemnisation d\'une assurance PE',
      'Identifier les entreprises qui ont le plus besoin de cette couverture',
      'Présenter les garanties spécifiques à l\'assurance vie de l\'entreprise',
      'Maîtriser les paramètres de tarification (période, marge brute)',
    ],
    cards: [
      { icon: '📉', title: 'Perte d\'exploitation', sub: 'Frais fixes + bénéfice' },
      { icon: '🔄', title: 'Indemnisation', sub: 'Mécanisme et calcul' },
      { icon: '⏱️', title: 'Période garantie', sub: 'Paramètre clé tarif' },
    ],
  },
  {
    num: '05',
    titleL1: 'RC Professionnelle',
    titleL2: '',
    domaine: 'produits',
    domaineLabel: "Produits d'assurance",
    meta: { duree: '2h', format: 'Hybride', public: 'Tous', mois: 'Mars 2026' },
    objectifs: [
      'Distinguer RC Exploitation et RC Professionnelle',
      'Maîtriser la loi Peeters-Ducarme pour les professions libérales',
      'Connaître la RC Décennale (loi Peeters-Borsus) et ses professions',
      'Identifier les informations nécessaires pour tarifier une RC Pro',
      'Conseiller efficacement un professionnel sur son niveau de couverture',
    ],
    cards: [
      { icon: '⚖️', title: 'Loi Peeters-Ducarme', sub: 'Professions libérales' },
      { icon: '🏗️', title: 'RC Décennale', sub: 'Loi Peeters-Borsus' },
      { icon: '💼', title: 'Tarification RC Pro', sub: 'Variables clés' },
    ],
  },
  {
    num: '06',
    titleL1: 'TRC',
    titleL2: 'Tous Risques Chantier',
    domaine: 'produits',
    domaineLabel: "Produits d'assurance",
    meta: { duree: '2h', format: 'Hybride', public: 'Tous', mois: 'Avril 2026' },
    objectifs: [
      'Définir ce qu\'est une assurance Tous Risques Chantier',
      'Identifier les parties prenantes d\'un chantier et leur rôle assurantiel',
      'Présenter le produit BeStronger Abonnement Allianz TRC',
      'Distinguer TRC, RC Décennale et RC Exploitation sur un chantier',
      'Maîtriser les informations nécessaires pour souscrire une police TRC',
    ],
    cards: [
      { icon: '🏗️', title: 'Tous Risques Chantier', sub: 'Couverture travaux' },
      { icon: '🤝', title: 'Allianz BeStronger', sub: 'TRC en abonnement' },
      { icon: '⚖️', title: 'RC Décennale', sub: 'Distinction légale' },
    ],
  },
  {
    num: '07',
    titleL1: 'Excel',
    titleL2: 'Maîtrise Gestion Client',
    domaine: 'digital',
    domaineLabel: 'Outils Digitaux',
    meta: { duree: '2h', format: 'À distance', public: 'Tous', mois: 'Avril 2026' },
    objectifs: [
      'Maîtriser les fonctions Excel essentielles pour le reporting client',
      'Construire un tableau de suivi de portefeuille clients',
      'Utiliser les tableaux croisés dynamiques pour analyser un portefeuille',
      'Automatiser des tâches répétitives avec des formules avancées',
      'Mettre en forme des données pour une présentation professionnelle',
    ],
    cards: [
      { icon: '📊', title: 'Tableaux croisés', sub: 'Analyse portefeuille' },
      { icon: '🔍', title: 'Formules avancées', sub: 'VLOOKUP, INDEX, MATCH' },
      { icon: '📈', title: 'Reporting client', sub: 'Présentation des données' },
    ],
  },
  {
    num: '08',
    titleL1: 'Pack HORECA',
    titleL2: '',
    domaine: 'produits',
    domaineLabel: "Produits d'assurance",
    meta: { duree: '2h', format: 'Hybride', public: 'Tous', mois: 'Mai 2026' },
    objectifs: [
      'Identifier les risques spécifiques du secteur HORECA',
      'Présenter les garanties du BeStronger Pack HORECA',
      'Maîtriser les informations nécessaires pour tarifier une police HORECA',
      'Reconnaître les situations à risque et les exclusions fréquentes',
      'Positionner l\'offre DAP face aux autres solutions du marché',
    ],
    cards: [
      { icon: '🍽️', title: 'Secteur HORECA', sub: '65 000 établissements BE' },
      { icon: '🛡️', title: 'BeStronger Pack', sub: 'Garanties spécifiques' },
      { icon: '⚠️', title: 'Risques & exclusions', sub: 'Points de vigilance' },
    ],
  },
  {
    num: '09',
    titleL1: 'Outlook',
    titleL2: 'Communication Client',
    domaine: 'digital',
    domaineLabel: 'Outils Digitaux',
    meta: { duree: '2h', format: 'À distance', public: 'Tous', mois: 'Mai 2026' },
    objectifs: [
      'Maîtriser l\'organisation des emails avec les dossiers et catégories',
      'Utiliser les règles automatiques pour trier sa boîte de réception',
      'Rédiger des emails professionnels conformes aux standards DAP',
      'Gérer les calendriers et les rendez-vous clients efficacement',
      'Utiliser les fonctionnalités avancées (rappels, suivi, modèles)',
    ],
    cards: [
      { icon: '📧', title: 'Organisation emails', sub: 'Dossiers & catégories' },
      { icon: '📅', title: 'Calendrier client', sub: 'Rendez-vous & suivi' },
      { icon: '✍️', title: 'Standards DAP', sub: 'Communication pro' },
    ],
  },
  {
    num: '10',
    titleL1: 'Responsabilité',
    titleL2: 'Contractuelle',
    domaine: 'assurances',
    domaineLabel: 'Gestion de sinistres',
    meta: { duree: '2h', format: 'Présentiel', public: 'Équipe Sinistres', mois: 'Juin 2026' },
    objectifs: [
      'Distinguer responsabilité contractuelle et extracontractuelle',
      'Identifier les conditions de mise en jeu d\'une responsabilité',
      'Appliquer ces notions à la gestion concrète d\'un dossier sinistre',
      'Connaître les règles de prescription en droit belge',
      'Maîtriser les principes d\'indemnisation et le calcul du préjudice',
    ],
    cards: [
      { icon: '📄', title: 'RC Contractuelle', sub: 'Obligations contractuelles' },
      { icon: '⚖️', title: 'RC Délictuelle', sub: 'Dommages extracontractuels' },
      { icon: '🔍', title: 'Gestion sinistres', sub: 'Application pratique' },
    ],
  },
  {
    num: '11',
    titleL1: 'BRIO',
    titleL2: "Pratiques d'Encodage",
    domaine: 'digital',
    domaineLabel: 'Outils Digitaux',
    meta: { duree: '4h', format: 'À distance', public: 'Tous', mois: 'Juin 2026' },
    objectifs: [
      'Maîtriser les standards d\'encodage DAP dans BRIO',
      'Créer et gérer les fiches clients avec toutes les informations requises',
      'Encoder correctement les polices, avenants et sinistres',
      'Utiliser les fonctionnalités de reporting de BRIO',
      'Adopter des pratiques uniformes garantissant la qualité des données',
    ],
    cards: [
      { icon: '💻', title: 'BRIO Platform', sub: 'Gestion courtage DAP' },
      { icon: '👤', title: 'Fiches clients', sub: 'Standards encodage' },
      { icon: '📊', title: 'Reporting BRIO', sub: 'Outils d\'analyse' },
    ],
  },
  {
    num: '12',
    titleL1: 'Assurance Vie',
    titleL2: '',
    domaine: 'produits',
    domaineLabel: "Produits d'assurance",
    meta: { duree: '2h', format: 'Présentiel', public: 'Tous', mois: 'Juillet 2026' },
    objectifs: [
      'Maîtriser les grandes catégories d\'assurance vie en Belgique (21, 23, 26)',
      'Distinguer assurance vie épargne, investissement et protection',
      'Connaître les avantages fiscaux liés à l\'assurance vie belge',
      'Identifier les informations obligatoires avant toute recommandation',
      'Appliquer les obligations MIFID/IDD lors du conseil en assurance vie',
    ],
    cards: [
      { icon: '🏦', title: 'Branches 21/23/26', sub: 'Catégories épargne' },
      { icon: '🎯', title: 'Avantages fiscaux', sub: 'Optimisation belge' },
      { icon: '📋', title: 'MIFID / IDD', sub: 'Obligations de conseil' },
    ],
  },
  {
    num: '13',
    titleL1: 'RGPD',
    titleL2: 'Protection des Données',
    domaine: 'reglementation',
    domaineLabel: 'Réglementation',
    meta: { duree: '2h', format: 'À distance', public: 'Tous', mois: 'Août 2026' },
    objectifs: [
      'Maîtriser les principes fondamentaux du RGPD pour un courtier',
      'Identifier les données personnelles traitées chez DAP et leurs bases légales',
      'Connaître les droits des personnes concernées et comment y répondre',
      'Appliquer les mesures de sécurité pour protéger les données clients',
      'Savoir quand et comment notifier une violation de données',
    ],
    cards: [
      { icon: '🔐', title: 'RGPD pratique', sub: 'Données personnelles' },
      { icon: '👤', title: 'Droits des personnes', sub: 'Réponses & obligations' },
      { icon: '🚨', title: 'Violation données', sub: 'Notification autorité' },
    ],
  },
  {
    num: '14',
    titleL1: 'Smile Assistance',
    titleL2: '',
    domaine: 'produits',
    domaineLabel: "Produits d'assurance",
    meta: { duree: '2h', format: 'Hybride', public: 'Tous', mois: 'Septembre 2026' },
    objectifs: [
      'Comprendre ce qu\'est une assurance assistance et ce qu\'elle apporte',
      'Présenter les garanties du produit Smile Assistance de BeStronger',
      'Distinguer assistance auto, habitation, voyage et personne',
      'Identifier les situations déclenchant l\'assistance',
      'Maîtriser le processus de déclaration d\'une demande d\'assistance',
    ],
    cards: [
      { icon: '🆘', title: 'Assistance auto', sub: 'Panne & accident' },
      { icon: '🏠', title: 'Assistance habitat', sub: 'Urgences domicile' },
      { icon: '✈️', title: 'Assistance voyage', sub: 'Couverture internationale' },
    ],
  },
  {
    num: '15',
    titleL1: 'Intelligence',
    titleL2: 'Artificielle',
    domaine: 'digital',
    domaineLabel: 'Outils Digitaux',
    meta: { duree: '4h', format: 'Présentiel', public: 'Tous', mois: 'Octobre 2026' },
    objectifs: [
      'Consolider les acquis des formations IA délivrées en 2025',
      'Identifier les usages concrets de l\'IA dans le métier de courtier',
      'Connaître et appliquer la charte IA de Feprabel',
      'Utiliser les outils IA disponibles chez DAP de façon responsable',
      'Comprendre les risques et limites de l\'IA dans un contexte assurantiel',
    ],
    cards: [
      { icon: '🤖', title: 'IA en courtage', sub: 'Usages concrets DAP' },
      { icon: '📜', title: 'Charte Feprabel', sub: 'Cadre éthique IA' },
      { icon: '⚠️', title: 'Risques & limites', sub: 'IA responsable' },
    ],
  },
  {
    num: '16',
    titleL1: 'Anti-Blanchiment',
    titleL2: 'AML',
    domaine: 'reglementation',
    domaineLabel: 'Réglementation',
    meta: { duree: '2h', format: 'À distance', public: 'Tous', mois: 'Octobre 2026' },
    objectifs: [
      'Comprendre ce qu\'est le blanchiment de capitaux et le financement du terrorisme',
      'Connaître les obligations légales AML applicables aux courtiers belges',
      'Appliquer la procédure de connaissance client (KYC) chez DAP',
      'Identifier les signaux d\'alerte (red flags) dans un dossier d\'assurance',
      'Savoir quand et comment effectuer une déclaration à la CTIF',
    ],
    cards: [
      { icon: '🔍', title: 'KYC & AML', sub: 'Connaissance client' },
      { icon: '🚩', title: 'Red flags', sub: 'Signaux d\'alerte' },
      { icon: '📋', title: 'Déclaration CTIF', sub: 'Procédure obligatoire' },
    ],
  },
  {
    num: '17',
    titleL1: 'Cybersécurité',
    titleL2: '',
    domaine: 'it',
    domaineLabel: 'IT',
    meta: { duree: '4h', format: 'À distance', public: 'Tous', mois: 'Novembre 2026' },
    objectifs: [
      'Identifier les principales cybermenaces auxquelles un courtier est exposé',
      'Reconnaître les tentatives de phishing et d\'ingénierie sociale',
      'Appliquer les bonnes pratiques de sécurité informatique au quotidien',
      'Connaître la procédure d\'incident de sécurité chez DAP',
      'Comprendre les obligations légales en matière de cybersécurité (NIS2)',
    ],
    cards: [
      { icon: '🎣', title: 'Phishing & Social', sub: 'Menaces principales' },
      { icon: '🔒', title: 'Bonnes pratiques', sub: 'Sécurité quotidienne' },
      { icon: '🚨', title: 'NIS2 & RGPD', sub: 'Obligations légales' },
    ],
  },
  {
    num: '18',
    titleL1: 'RoadShow',
    titleL2: 'Euromex & Baloise',
    domaine: 'produits',
    domaineLabel: "Produits d'assurance",
    meta: { duree: '4h', format: 'Présentiel', public: 'Tous', mois: 'Décembre 2026' },
    objectifs: [
      'Connaître les nouveautés produits Euromex pour l\'exercice 2026-2027',
      'Connaître les nouveautés produits Baloise pour l\'exercice 2026-2027',
      'Identifier les opportunités commerciales issues de ces évolutions',
      'Savoir adapter les offres DAP aux nouvelles garanties disponibles',
      'Mettre à jour ses connaissances sur les tarifs et conditions de souscription',
    ],
    cards: [
      { icon: '🏢', title: 'Euromex 2026-27', sub: 'Nouveautés produits' },
      { icon: '🏦', title: 'Baloise 2026-27', sub: 'Nouveautés produits' },
      { icon: '💼', title: 'Opportunités DAP', sub: 'Adaptations offres' },
    ],
  },
  {
    num: '19',
    titleL1: 'Microsoft Teams',
    titleL2: '',
    domaine: 'digital',
    domaineLabel: 'Outils Digitaux',
    meta: { duree: '2h', format: 'À distance', public: 'Tous', mois: 'Décembre 2026' },
    objectifs: [
      'Maîtriser les fonctionnalités essentielles de Microsoft Teams',
      'Organiser efficacement les canaux et équipes dans Teams',
      'Conduire des réunions professionnelles dans Teams',
      'Utiliser Teams pour la collaboration sur les documents (OneDrive)',
      'Appliquer les bonnes pratiques de communication interne DAP',
    ],
    cards: [
      { icon: '💬', title: 'Canaux Teams', sub: 'Communication interne' },
      { icon: '🎥', title: 'Réunions Teams', sub: 'Conduire efficacement' },
      { icon: '📁', title: 'OneDrive intégré', sub: 'Collaboration docs' },
    ],
  },
];
